// // types/NotificationItem.ets
//
// export class NotificationItem {
//   id: number;
//   title: string;
//   content: string;
//   date: string;
//   read: boolean;
//
//   constructor(
//     id: number,
//     title: string,
//     content: string,
//     date: string,
//     read: boolean
//   ) {
//     this.id = id;
//     this.title = title;
//     this.content = content;
//     this.date = date;
//     this.read = read;
//   }
// }